# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CveeI63CSqmPtu9CJN4hL2H0QycfQFMu
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, accuracy_score
from sklearn.impute import SimpleImputer
from plotnine import *

# Load the data into a Pandas dataframe
file_path = '/content/Dataset(Vedio_Game_Sale_Prediction).csv'
df = pd.read_csv(file_path)

# Handling missing values
df.fillna(df.mean(), inplace=True)  # You can use other imputation strategies based on your data

# Linear Regression for Global Sales
X_linear = df[['Year_of_Release', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']]
y_linear = df['Global_Sales']

X_train_linear, X_test_linear, y_train_linear, y_test_linear = train_test_split(X_linear, y_linear, test_size=0.2, random_state=42)

lr_global_sales = LinearRegression()
lr_global_sales.fit(X_train_linear, y_train_linear)
y_pred_linear = lr_global_sales.predict(X_test_linear)
accuracy_linear = r2_score(y_test_linear, y_pred_linear)
print('Linear Regression Accuracy (Global Sales):', accuracy_linear)

# Polynomial Regression for Global Sales
poly_global_sales = PolynomialFeatures(degree=2)
X_poly = poly_global_sales.fit_transform(X_train_linear)
poly_reg = LinearRegression()
poly_reg.fit(X_poly, y_train_linear)
y_pred_poly = poly_reg.predict(poly_global_sales.transform(X_test_linear))
accuracy_poly_global_sales = r2_score(y_test_linear, y_pred_poly)
print('Polynomial Regression Accuracy (Global Sales):', accuracy_poly_global_sales)

# Multiple Regression for Global Sales
multi_global_sales = LinearRegression()
multi_global_sales.fit(X_train_linear, y_train_linear)
y_pred_multi = multi_global_sales.predict(X_test_linear)
accuracy_multi_global_sales = r2_score(y_test_linear, y_pred_multi)
print('Multiple Regression Accuracy (Global Sales):', accuracy_multi_global_sales)

p_linear = (ggplot(df, aes(x='Year_of_Release', y='Global_Sales')) +
            geom_point() +
            geom_smooth(method='lm', se=False, color='red') +
            ggtitle('Linear Regression of Global Sales vs Year_of_Release')
)
p_linear.draw()